### PR TITLE
migrate to use Settings DSL

### PR DESCRIPTION
**Pull request by evgeni**

### CODE REVIEW

**Comment by evgeni** [comment]
includes #84 to see if stuff actually works

**Review by ares — APPROVED** [review]
I haven't tested but I think you got it all

**Comment by evgeni** [comment]
CI still fails because it needs #85 for the Puppet Environment fix (chicken, egg)

**Comment by ekohl** [comment]
I merged the others. Rebased to see if it now passes.

**Review by ekohl — APPROVED** [review]
Only 3.3 is still running.

**Pull request merged**
