### PR TITLE
Release 3.0.0

### PR DESCRIPTION
**Pull request by evgeni**

### CODE REVIEW

**Comment by evgeni** [comment]
:eyes: @dgoetz @timogoebel

**Comment by evgeni** [comment]
(I am able to cut the release myself, but kinda didn't want to go past you)

**Comment by evgeni** [comment]
Seems there are still issues for the user: https://community.theforeman.org/t/foreman-3-4-stable-unknown-attribute-description-for-setting-foremanhostextravalidator/30333/42?u=evgeni

**Comment by evgeni** [comment]
The fix is merged (#87), so we can go forth with the release now.

**Comment by janfickler** [comment]
could this please be pushed forward :-)
i am still missing the fix for the monitoring plugin.

**Comment by dgoetz** [comment]
@janfickler I did the release and also packaging for deb and rpm for nightly and 3.4 today, so the fix should be available soon for you.

**Pull request merged**
