### PR TITLE
Update target Ruby version to 2.3 for RuboCop

### PR DESCRIPTION
**Pull request by ananace**
To fix the tests (as shown in #59)

### CODE REVIEW

**Comment by timogoebel** [comment]
@ananace: I think we need to pin this plugins rubocop version (in the gemspec) to the version currently being used in core's develop branch.

**Comment by ananace** [comment]
That's also a solution I guess, though it feels odd to have an active development branch being linted against an End-of-Life version of Ruby

**Comment by timogoebel** [comment]
@ananace: I think you need to do both actually.

**Comment by ananace** [comment]
And also needs a whole lot of `# frozen_string_literal: true` apparently.

I'll push an update in a few minutes

**Comment by ananace** [comment]
Right, the only broken tests still look like something that can't be solved in the context of foreman_monitoring.

Or at least they *should* not be fixed in the context of foreman_monitoring.

**Comment by timogoebel** [comment]
Thanks, @ananace.

**Pull request merged**
