### PR TITLE
add grace time for result uploads

### PR DESCRIPTION
**Pull request by timogoebel**
@dgoetz, @hboetes: Do you mind taking a look? Does this solve the issue for you?

@Thomas-Gelf already approved. :-)

### CODE REVIEW

**Comment by hboetes** [comment]
I’m on vacation now, guys. But I’m happy you found the bug and will test it in 2 weeks!

**Comment by dgoetz** [comment]
I tested it and can also confirm it working now as expected and I think two seconds is not so much that it likely will cause problems even if initial sync runs and status change event happens during it.

**Comment by timogoebel** [comment]
@dgoetz: Thanks for confirming.

I fixed the rubocop warning. We can merge, once tests are 🍏.

**Comment by timogoebel** [comment]
Merged and cherry-picked to `0.1-stable` as 974e82325e44c23a5e7e53eef20617c6888998c8.

**Pull request merged**
