### PR TITLE
Fixes #28985 - Add description to plugin roles

### PR DESCRIPTION
**Pull request by stejskalleos**
PR is part of  [Add default descriptions to all roles added from plugins](https://projects.theforeman.org/issues/28936) task.

### CODE REVIEW

**Comment by stejskalleos** [comment]
Hi @dgoetz , can you please give me some good description for the roles? Thanks

**Comment by dgoetz** [comment]
Hi @stejskalleos, I had this on my list for today, but you were faster. I pushed a small change into your branch. If you do not think the description is now to long, I would be good to merge after tests are green.

**Comment by stejskalleos** [comment]
Hi @dgoetz, looks good to me!
Thank you

**Comment by dgoetz** [comment]
Merged, thank you!

**Pull request merged**
