### PR TITLE
fix rubocop hash alignment

### PR DESCRIPTION
**Pull request by dgoetz**
Trying to fix the "Align the elements of a hash literal if they span more than one line." messages

### CODE REVIEW

**Comment by dgoetz** [comment]
Tests run fine with the fixes. I also tried table style for the alignment, but this would have been more changes.

**Comment by timogoebel** [comment]
@dgoetz: Thanks, do you mind bumping the rubocop version to `0.64.0` in the gemspec so it matches the version in core (that is unfortunately used for tests).

**Comment by dgoetz** [comment]
I bumped the version, tests are still fine.

**Comment by timogoebel** [comment]
Thanks, @dgoetz.

**Pull request merged**
